#!/bin/bash

# 🎯 Script de Vérification Configuration Railway

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     🔍 VÉRIFICATION CONFIGURATION RAILWAY - CORS FIX        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 CHECKLIST À VÉRIFIER DANS RAILWAY DASHBOARD :"
echo ""

echo "┌──────────────────────────────────────────────────────────────┐"
echo "│  1️⃣  FRONTEND SERVICE → Variables                            │"
echo "└──────────────────────────────────────────────────────────────┘"
echo ""
echo "  ❌ SUPPRIME complètement (ne doit PAS exister) :"
echo "     REACT_APP_API_URL"
echo ""
echo "  ✅ DOIT AVOIR ces variables :"
echo "     CI=false"
echo "     NODE_ENV=production"
echo "     GENERATE_SOURCEMAP=false"
echo "     BACKEND_URL=https://authentic-intuition-production-ec05.up.railway.app"
echo ""

echo "┌──────────────────────────────────────────────────────────────┐"
echo "│  2️⃣  BACKEND SERVICE → Variables                             │"
echo "└──────────────────────────────────────────────────────────────┘"
echo ""
echo "  ✅ DOIT AVOIR ces variables :"
echo "     CORS_ORIGIN=https://gressy-gestion-laiterie-projet.up.railway.app"
echo "     NODE_ENV=production"
echo "     JWT_SECRET=<secret-fort>"
echo "     DB_HOST=<mysql-host>"
echo "     DB_USER=<mysql-user>"
echo "     DB_PASSWORD=<mysql-password>"
echo "     DB_NAME=<database-name>"
echo ""

echo "┌──────────────────────────────────────────────────────────────┐"
echo "│  3️⃣  FORCER NOUVEAU BUILD                                    │"
echo "└──────────────────────────────────────────────────────────────┘"
echo ""
echo "  Après avoir supprimé REACT_APP_API_URL :"
echo ""
echo "  Option A - Trigger Rebuild automatique :"
echo "    - Push un commit (celui-ci par exemple)"
echo "    - Railway rebuild automatiquement"
echo ""
echo "  Option B - Rebuild manuel :"
echo "    - Railway Dashboard → Frontend Service → Deployments"
echo "    - Clique sur ... du dernier deployment"
echo "    - Clique sur 'Redeploy'"
echo ""
echo "  ⚠️  IMPORTANT : Le nouveau build ne doit PAS avoir REACT_APP_API_URL"
echo ""

echo "┌──────────────────────────────────────────────────────────────┐"
echo "│  4️⃣  VÉRIFICATION LOGS FRONTEND                             │"
echo "└──────────────────────────────────────────────────────────────┘"
echo ""
echo "  Après redéploiement, dans les logs frontend, tu DOIS voir :"
echo ""
echo "  🔗 Backend API URL: https://authentic-intuition-production-ec05.up.railway.app"
echo ""
echo "  Et quand tu te connectes :"
echo ""
echo "  2026-01-02T... POST /api/auth/login"
echo "  🔄 Proxying: POST /api/auth/login → https://authentic-intuition..."
echo "  ✅ Proxy response: 200 /api/auth/login"
echo ""
echo "  ❌ Si tu vois des requêtes DIRECTES vers authentic-intuition..."
echo "     → REACT_APP_API_URL est encore définie quelque part"
echo ""

echo "┌──────────────────────────────────────────────────────────────┐"
echo "│  5️⃣  TEST FINAL                                              │"
echo "└──────────────────────────────────────────────────────────────┘"
echo ""
echo "  1. Ouvre : https://gressy-gestion-laiterie-projet.up.railway.app"
echo "  2. Ouvre DevTools (F12) → Network tab"
echo "  3. Essaie de te connecter"
echo "  4. Regarde les requêtes :"
echo ""
echo "  ✅ CORRECT : POST https://gressy-gestion-laiterie-projet.up.railway.app/api/auth/login"
echo "  ❌ INCORRECT : POST https://authentic-intuition-production-ec05.up.railway.app/api/auth/login"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  📚 Documentation : RAILWAY_CORS_FINAL_FIX.md               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
