[phases.setup]
nixPkgs = ['nodejs-18_x', 'openssl']

[phases.install]
cmds = [
  'cd server && npm install'
]

[phases.build]
# Pas de build nécessaire pour le backend seul

[start]
cmd = 'cd server && node index.js'

[variables]
NODE_ENV = 'production'
